version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

executors:
  jdk:
    docker:
      - image: openjdk:17-jdk-slim
  jdk-full:
    docker:
      - image: openjdk:17-jdk

commands:
  with_cache:
    parameters:
      steps:
        type: steps
    steps:
      - restore_cache:
          keys:
            - v2-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle/libs.versions.toml" }}
            - v2-{{ checksum "build.gradle.kts" }}
            - v2-
      - steps: << parameters.steps >>

jobs:
  compile:
    executor: jdk
    steps:
      - checkout
      - with_cache:
          steps:
            - run:
                command: ./gradlew classes
                name: Compiling main classes
            - save_cache:
                key: v2-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle/libs.versions.toml" }}
                paths:
                  - ~/.gradle
            - persist_to_workspace:
                root: .
                paths:
                  - build
                  - buildSrc/build

  check:
    executor: jdk-full
    steps:
      - checkout
      - with_cache:
          steps:
            - attach_workspace:
                at: .
            - run:
                command: ./gradlew check
                name: Running tests
            - store_test_results:
                path: build/test-results
            - store_artifacts:
                path: build/reports
            - codecov/upload

workflows:
  full_workflow:
    jobs:
      - compile
      - check:
          requires:
            - compile
