name: Main
on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  check:
    name: Test and Lint
    runs-on: ubuntu-latest
    container: eclipse-temurin:17
  steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Run checks
      run: ./gradlew check
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
